export const sidebarItems = [
{type: 'folder', folderName: 'auth', mdNameList: [ 'aws-cognito'], mdFileName: null, filePath: '/auth/'},
{type: 'folder', folderName: 'data-fetching', mdNameList: [ 'axios', 'react-query', 'swr'], mdFileName: null, filePath: '/data-fetching/'},
{type: 'folder', folderName: 'forms', mdNameList: [ 'formik', 'react-hook-form', 'storing-in-local-storage', 'validation'], mdFileName: null, filePath: '/forms/'},
{type: 'folder', folderName: 'general', mdNameList: [ 'constants'], mdFileName: null, filePath: '/general/'},
{type: 'folder', folderName: 'git-flow', mdNameList: [ 'github-actions'], mdFileName: null, filePath: '/git-flow/'},
{type: 'folder', folderName: 'git', mdNameList: [ 'git', 'git_copy'], mdFileName: null, filePath: '/git/'},
{type: 'folder', folderName: 'ide-extensions', mdNameList: [ 'vscode'], mdFileName: null, filePath: '/ide-extensions/'},
{type: 'folder', folderName: 'internationalization', mdNameList: [ 'i18next', 'lingui-js', 'react-intl'], mdFileName: null, filePath: '/internationalization/'},
{type: 'folder', folderName: 'monitoring', mdNameList: [ 'sentry'], mdFileName: null, filePath: '/monitoring/'},
{type: 'folder', folderName: 'notifications', mdNameList: [ 'circle-ci-slack', 'jira-github'], mdFileName: null, filePath: '/notifications/'},
{type: 'folder', folderName: 'roles-and-permissions', mdNameList: [ 'roles-and-permissions'], mdFileName: null, filePath: '/roles-and-permissions/'},
{type: 'folder', folderName: 'router', mdNameList: [ 'leave-modal'], mdFileName: null, filePath: '/router/'},
{type: 'folder', folderName: 'ssr', mdNameList: [ 'general', 'next-js-13', 'next-js'], mdFileName: null, filePath: '/ssr/'},
{type: 'folder', folderName: 'context', mdNameList: [ 'react-context-api', 'react-context-useReducer', 'ref-based-context-api'], mdFileName: null, filePath: '/state-management//context/'},
{type: 'folder', folderName: 'state-management', mdNameList: [ '*'], mdFileName: null, filePath: '/state-management/'},
{type: 'folder', folderName: 'styling', mdNameList: [ 'MUI', 'dark-mode', 'general-recommendations', 'styled-components'], mdFileName: null, filePath: '/styling/'},
{type: 'folder', folderName: 'WYSIWYG', mdNameList: [ 'tip-tap'], mdFileName: null, filePath: '/ui-components//WYSIWYG/'},
{type: 'folder', folderName: 'ui-components', mdNameList: [ 'otp-input'], mdFileName: null, filePath: '/ui-components/'},
{type: 'folder', folderName: '.', mdNameList: [ '*'], mdFileName: null, filePath: ''},
];
